title: DW Guide
description: Welcome to Dnd World, the largest text-based D&D living world!
theme: just-the-docs
color_scheme: dw

url: https://jmac-0904.github.io/jmactest-justthedocs/

aux_links:
  "About Us": 
    - "https://jmac-0904.github.io/jmactest-justthedocs/"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
